# Generated by Django 4.0 on 2022-06-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
